### ISSUE TITLE
hello，flutter 项目集成 wechat_kit 之后登录没有走回调

### ISSUE THREAD

**Issue by hw20101101** [RxReader/wechat_kit#83]
**问题详情  **
我在 iPhone 上面运行 flutter 项目之后，在登录界面点击微信登录按钮，跳转到微信并确认登录，然后返回到我的 App之后没有走 flutter 的登录回调。

**项目环境  **
```
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  wechat_kit: ^2.3.1

```

```
[✓] Flutter (Channel stable, 2.0.6, on Mac OS X 10.15.7 19H15 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode v12.4 - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.57.0)
[✓] Connected device (2 available)
       iPhone 6 Plus - iOS 12.4
```

> 注：iOS 项目中已经配置了 weixin 的 URL types 和 Schemes
